name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 4.0.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  nylo_support: ^4.0.0
  theme_provider: ^0.5.0
  json_dart_generator: ^1.1.0+1
  page_transition: ^2.0.9
  args: ^2.3.1
  recase: ^4.1.0
  flutter:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

